apiVersion: apps/v1
kind: Deployment
metadata:
  name: media
  namespace: merchshop
  labels:
    app: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
        - name: media
          image: media:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8083
            - name: grpc
              containerPort: 50051
          envFrom:
            - configMapRef:
                name: media-config
            - secretRef:
                name: media-secrets
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
