apiVersion: v1
kind: Secret
metadata:
  name: media-secrets
  namespace: merchshop
  labels:
    app: media
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "change-me-access-secret-min-32-characters-long"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
