apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: merchshop
  labels:
    app: user
data:
  POSTGRES_HOST: "host.minikube.internal"
  POSTGRES_PORT: "5433"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "merch_users"
  POSTGRES_SSLMODE: "disable"
  REDIS_HOST: "host.minikube.internal"
  REDIS_PORT: "6379"
  GRPC_PORT: "50051"
  HTTP_PORT: "8081"
  COOKIE_SECURE: "false"
  COOKIE_SAMESITE: "lax"
