apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: merchshop
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
            - name: grpc
              containerPort: 50051
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: user-secrets
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
