apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: merchshop
  labels:
    app: product
data:
  POSTGRES_HOST: "host.minikube.internal"
  POSTGRES_PORT: "5433"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "merch_products"
  POSTGRES_SSLMODE: "disable"
  GRPC_PORT: "50051"
  HTTP_PORT: "8082"
