apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
  namespace: merchshop
  labels:
    app: product
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "change-me-access-secret-min-32-characters-long"
  POSTGRES_PASSWORD: "changeme"
