services:
  user: http://user:8081
  product: http://product:8082
  media: http://media:8083
  inventory: http://inventory:8084
  cart: http://cart:8085
  order: http://order:8086

routes:
  - prefix: /api/v1/auth/*
    service: user
    public: true
  - prefix: /api/v1/me
    service: user


  - prefix: /api/v1/products
    service: product
  - prefix: /api/v1/categories
    service: product


  - prefix: /api/v1/admin/products
    service: product
  - prefix: /api/v1/admin/categories
    service: product


  - prefix: /api/v1/admin/media
    service: media

  - prefix: /api/v1/stock
    service: inventory

  - prefix: /api/v1/admin/inventory
    service: inventory

  - prefix: /api/v1/cart
    service: cart

  - prefix: /api/v1/orders
    service: order

  - prefix: /api/v1/admin/orders
    service: order

  - prefix: /api/v1/admin/analytics
    service: order

  - prefix: /api/v1/admin/users
    service: user
