services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      HTTP_PORT: 8080
      GATEWAY_ROUTES: /api/v1/auth=http://user:8081,/api/v1/me=http://user:8081
      GATEWAY_PUBLIC_PREFIXES: /api/v1/auth/login,/api/v1/auth/register,/api/v1/auth/refresh
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    external: true
    name: user_default
