apiVersion: v1
kind: Secret
metadata:
  name: cart-secrets
  namespace: merchshop
  labels:
    app: cart
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "change-me-access-secret-min-32-characters-long"
  POSTGRES_PASSWORD: "changeme"
  REDIS_PASSWORD: "changeme"
