apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: merchshop
  labels:
    app: cart
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
    - name: http
      port: 8085
      targetPort: 8085
    - name: grpc
      port: 50055
      targetPort: 50055
