// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: media.proto

package mediapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Один элемент потока загрузки: либо метаданные (ровно первым), либо чанк данных.
type UploadPhotoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadPhotoRequest_Metadata
	//	*UploadPhotoRequest_Data
	Payload       isUploadPhotoRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPhotoRequest) Reset() {
	*x = UploadPhotoRequest{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPhotoRequest) ProtoMessage() {}

func (x *UploadPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPhotoRequest.ProtoReflect.Descriptor instead.
func (*UploadPhotoRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadPhotoRequest) GetPayload() isUploadPhotoRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadPhotoRequest) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadPhotoRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadPhotoRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadPhotoRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadPhotoRequest_Payload interface {
	isUploadPhotoRequest_Payload()
}

type UploadPhotoRequest_Metadata struct {
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadPhotoRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadPhotoRequest_Metadata) isUploadPhotoRequest_Payload() {}

func (*UploadPhotoRequest_Data) isUploadPhotoRequest_Payload() {}

// Метаданные загружаемого файла. Идут первым message в потоке.
type UploadMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // image/jpeg | image/png | image/webp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// Ключ сохранённого объекта, например products/{uuid}.jpg.
type PhotoKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhotoKey      string                 `protobuf:"bytes,1,opt,name=photo_key,json=photoKey,proto3" json:"photo_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhotoKey) Reset() {
	*x = PhotoKey{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhotoKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhotoKey) ProtoMessage() {}

func (x *PhotoKey) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhotoKey.ProtoReflect.Descriptor instead.
func (*PhotoKey) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *PhotoKey) GetPhotoKey() string {
	if x != nil {
		return x.PhotoKey
	}
	return ""
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\x05media\"j\n" +
	"\x12UploadPhotoRequest\x123\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.media.UploadMetadataH\x00R\bmetadata\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"O\n" +
	"\x0eUploadMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"'\n" +
	"\bPhotoKey\x12\x1b\n" +
	"\tphoto_key\x18\x01 \x01(\tR\bphotoKey2K\n" +
	"\fMediaService\x12;\n" +
	"\vUploadPhoto\x12\x19.media.UploadPhotoRequest\x1a\x0f.media.PhotoKey(\x01BQZOgithub.com/mihnpro/Merch_shop/services/media/api/server/AccountInternal;mediapbb\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_media_proto_goTypes = []any{
	(*UploadPhotoRequest)(nil), // 0: media.UploadPhotoRequest
	(*UploadMetadata)(nil),     // 1: media.UploadMetadata
	(*PhotoKey)(nil),           // 2: media.PhotoKey
}
var file_media_proto_depIdxs = []int32{
	1, // 0: media.UploadPhotoRequest.metadata:type_name -> media.UploadMetadata
	0, // 1: media.MediaService.UploadPhoto:input_type -> media.UploadPhotoRequest
	2, // 2: media.MediaService.UploadPhoto:output_type -> media.PhotoKey
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	file_media_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadPhotoRequest_Metadata)(nil),
		(*UploadPhotoRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
