apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: merchshop
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: inventory:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8084
            - name: grpc
              containerPort: 50051
          envFrom:
            - configMapRef:
                name: inventory-config
            - secretRef:
                name: inventory-secrets
          readinessProbe:
            tcpSocket:
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8084
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
